version: "3"

services:
  gateway:
    container_name: api_gateway
    build:
      dockerfile: api-gateway/Dockerfile
      target: development
      context: .
    volumes:
      - ./api-gateway:/usr/src/app
    command: npm run start:dev
    networks:
      - moomoo-services
    ports:
      - 3000:3000
  user:
    container_name: user_service
    build:
      dockerfile: user/Dockerfile
      target: development
      context: .
    volumes:
      - ./user:/usr/src/app
    command: npm run start:dev
    networks:
      - moomoo-services
  queue:
    container_name: queue
    image: rabbitmq:management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=testpassword
    networks:
      - moomoo-services

networks:
  moomoo-services:
    external: true
